services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: airgap_backend:${AIRGAP_BACKEND_VERSION:-latest}
    restart: always
    env_file:
      - path: .env
        required: false
    depends_on:
      db:
        condition: service_healthy
      rmq:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      AIRGAP_BACKEND_HOST: 0.0.0.0
      AIRGAP_BACKEND_DB_HOST: airgap_backend-db
      AIRGAP_BACKEND_DB_PORT: 5432
      AIRGAP_BACKEND_DB_USER: airgap_backend
      AIRGAP_BACKEND_DB_PASS: airgap_backend
      AIRGAP_BACKEND_DB_BASE: airgap_backend
      AIRGAP_BACKEND_RABBIT_HOST: airgap_backend-rmq

  taskiq-worker:
    <<: *main_app
    labels: []
    command:
      - taskiq
      - worker
      - airgap_backend.tkq:broker

  db:
    image: postgres:18.1-bookworm
    hostname: airgap_backend-db
    environment:
      POSTGRES_PASSWORD: "airgap_backend"
      POSTGRES_USER: "airgap_backend"
      POSTGRES_DB: "airgap_backend"
    volumes:
      - airgap_backend-db-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: pg_isready -U airgap_backend
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    <<: *main_app
    restart: "no"
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy

  rmq:
    image: rabbitmq:4.2.1-management-alpine
    hostname: "airgap_backend-rmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50



volumes:
  airgap_backend-db-data:
    name: airgap_backend-db-data
